repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      description: Run ruff linting
      entry: poetry run ruff check --force-exclude
      language: system
      'types_or': [python, pyi]
      require_serial: true
      args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
